<?php

/**
 * Created by PhpStorm.
 * User: usman.khan
 * Date: 6/15/16
 * Time: 6:29 AM
 */
class TeacherView extends AbstractView
{
    public function render($name)
    {
        $url='views/teacher/'.$name.'.php';
        if (file_exists($url))
            require 'views/teacher/'.$name.'.php';
    }
    public function preDisplay($arr)
    {
//parent::preDisplay($arr); // TODO: Change the autogenerated stub
    }
}